import { Injectable } from '@nestjs/common';
import * as fs from 'fs';

/** Minimal request facts the config is derived from (kept framework-free for tests). */
export interface WebClientRequestInfo {
  host?: string;
  protocol?: string;
}

export interface WebClientConfig {
  enabled: boolean;
  /** Rendezvous (hbbs) server, `host` or `host:port` (port defaults to 21116 in the client). */
  id_server: string;
  /** Relay (hbbr) server, informational: the web client derives it from id_server (+3). */
  relay_server: string;
  /** Console API server URL (scheme + host) the web client talks to for login/address book. */
  api_server: string;
  /** Server public key (contents of id_ed25519.pub); empty when not configured. */
  key: string;
}

const HOST_RE = /^[A-Za-z0-9.-]+(:\d{1,5})?$|^\[[0-9A-Fa-f:]+\](:\d{1,5})?$/;

/**
 * Web client configuration.
 *
 * Self-contained on purpose: values come from environment variables so this
 * can later be reconciled with a settings-backed "client setup" API.
 *
 * - WEB_CLIENT_ENABLED      "false"/"0" disables the endpoints (default: enabled)
 * - WEB_CLIENT_ID_SERVER    id/rendezvous server, host[:port] (default: request host, no port)
 * - WEB_CLIENT_RELAY_SERVER relay server (default: same as id server)
 * - WEB_CLIENT_API_SERVER   console URL, e.g. https://rd.example.com (default: request origin)
 * - WEB_CLIENT_KEY          server public key; or RUSTDESK_KEY_FILE pointing at id_ed25519.pub
 */
@Injectable()
export class WebClientService {
  isEnabled(): boolean {
    const v = process.env.WEB_CLIENT_ENABLED?.trim().toLowerCase();
    return !(v === 'false' || v === '0' || v === 'no');
  }

  getConfig(req: WebClientRequestInfo): WebClientConfig {
    const requestHost = this.sanitizeHost(req.host);
    const hostname = requestHost ? this.stripPort(requestHost) : '';
    const idServer =
      this.sanitizeHost(process.env.WEB_CLIENT_ID_SERVER) || hostname;
    const relayServer =
      this.sanitizeHost(process.env.WEB_CLIENT_RELAY_SERVER) || idServer;
    const proto = req.protocol === 'https' ? 'https' : 'http';
    const apiServer =
      process.env.WEB_CLIENT_API_SERVER?.trim().replace(/\/+$/, '') ||
      (requestHost ? `${proto}://${requestHost}` : '');
    return {
      enabled: this.isEnabled(),
      id_server: idServer,
      relay_server: relayServer,
      api_server: apiServer,
      key: this.readKey(),
    };
  }

  /**
   * JavaScript loaded by the web client's index.html (`/webclient-config/index.js`)
   * before the app starts. It pre-seeds the localStorage keys the client reads.
   * Values are emitted with JSON.stringify (and U+2028/2029 escaped), never concatenated raw.
   */
  renderConfigScript(cfg: WebClientConfig): string {
    const js = (v: string) =>
      JSON.stringify(v)
        .replace(/\u2028/g, '\\u2028')
        .replace(/\u2029/g, '\\u2029')
        .replace(/</g, '\\u003c');
    const lines = [
      '// Generated by the console: GET /api/web-client/config.js',
    ];
    if (cfg.enabled) {
      if (cfg.id_server) {
        lines.push(
          `localStorage.setItem('custom-rendezvous-server', ${js(cfg.id_server)});`,
        );
      }
      if (cfg.key) lines.push(`localStorage.setItem('key', ${js(cfg.key)});`);
      if (cfg.api_server) {
        lines.push(
          `localStorage.setItem('api-server', ${js(cfg.api_server)});`,
        );
      }
    }
    return lines.join('\n') + '\n';
  }

  private readKey(): string {
    const direct = process.env.WEB_CLIENT_KEY?.trim();
    if (direct) return direct;
    const file = process.env.RUSTDESK_KEY_FILE?.trim();
    if (!file) return '';
    try {
      return fs.readFileSync(file, 'utf8').trim();
    } catch {
      return '';
    }
  }

  private sanitizeHost(raw?: string): string {
    const v = raw?.split(',')[0]?.trim() ?? '';
    return v && HOST_RE.test(v) ? v : '';
  }

  private stripPort(hostPort: string): string {
    if (hostPort.startsWith('[')) {
      return hostPort.slice(0, hostPort.indexOf(']') + 1);
    }
    return hostPort.split(':')[0];
  }
}
